name: Build Android APK

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ runner.temp }}/android-sdk
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Debug environment
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          ls -R "$ANDROID_HOME" | head -100

      - name: Install Android SDK command-line tools
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          cd "$ANDROID_HOME"
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          unzip -q cmdline.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root="$ANDROID_HOME" "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Download Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.1.1-bin.zip -O gradle.zip
          unzip -q gradle.zip

      - name: Build debug APK
        run: |
          ./gradle-8.1.1/bin/gradle assembleDebug --no-daemon --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: simple-ac-scan-apk
          path: app/build/outputs/apk/debug/app-debug.apk
